.TH "clipboard" "1" "January 2022" "" ""
.hy
.SH NAME
.PP
clipboard - a better cli clipboard
.SH Examples
.PP
\f[B]Copy to os clipbard\f[R]
.PP
cb package.json
.PP
\f[B]Pipe to os clipboard\f[R]
.PP
cat package.json | cb echo `Hello World!' | cb
.PP
\f[B]Read clipboard contents\f[R]
.PP
cb | vim -
.PP
\f[B]Search clipboard contents\f[R]
.PP
cb | grep hello
.SH AUTHORS
Amila Welihinda.