//! Clipboard questions arboard doesn't answer, asked the way each platform
//! expects: whether a copy was marked as not to be recorded, as password
//! managers do, and whether the clipboard changed at all.
//!
//! When the check itself fails, the copy is taken to be unmarked. Otherwise
//! history would stop working anywhere the check can't run.

pub use imp::{change_count, is_concealed};

/// Linux and the BSDs, on X11 or Wayland.
#[cfg(all(
    unix,
    not(any(target_os = "macos", target_os = "android", target_os = "emscripten"))
))]
mod imp {
    use std::env;
    use std::thread;
    use std::time::{Duration, Instant};

    use wl_clipboard_rs::paste::{get_mime_types, ClipboardType, Seat};
    use x11rb::connection::Connection;
    use x11rb::protocol::xproto::{AtomEnum, ConnectionExt, CreateWindowAux, WindowClass};
    use x11rb::protocol::Event;

    /// Introduced by KDE's clipboard manager, and set by password managers
    /// like KeePassXC.
    const HINT: &str = "x-kde-passwordManagerHint";

    /// How long the clipboard's owner gets to list what it offers.
    const TIMEOUT: Duration = Duration::from_millis(500);

    /// X11 and Wayland have no cheap change counter, so the watcher reads the
    /// clipboard every time.
    pub fn change_count() -> Option<u64> {
        None
    }

    pub fn is_concealed() -> bool {
        // A Wayland program without focus can only see the clipboard through
        // the data-control protocol, which some compositors, like GNOME's,
        // lack. X11 is the fallback, as it is for arboard, and XWayland
        // mirrors the clipboard there.
        if env::var_os("WAYLAND_DISPLAY").is_some() {
            if let Ok(types) = get_mime_types(ClipboardType::Regular, Seat::Unspecified) {
                return types.contains(HINT);
            }
        }
        x11_offers(HINT).unwrap_or(false)
    }

    /// Whether the owner of the X11 clipboard lists `target` among the
    /// formats it offers.
    fn x11_offers(target: &str) -> Option<bool> {
        let (conn, screen) = x11rb::connect(None).ok()?;
        let atom = |name: &str, only_if_exists: bool| -> Option<u32> {
            let cookie = conn.intern_atom(only_if_exists, name.as_bytes()).ok()?;
            Some(cookie.reply().ok()?.atom)
        };
        // Nobody can offer a format that no program has named.
        let target = atom(target, true)?;
        if target == x11rb::NONE {
            return Some(false);
        }
        let clipboard = atom("CLIPBOARD", false)?;
        let targets = atom("TARGETS", false)?;
        let property = atom("CB_TARGETS", false)?;

        let window = conn.generate_id().ok()?;
        let root = conn.setup().roots.get(screen)?.root;
        conn.create_window(
            x11rb::COPY_DEPTH_FROM_PARENT,
            window,
            root,
            0,
            0,
            1,
            1,
            0,
            WindowClass::INPUT_ONLY,
            x11rb::COPY_FROM_PARENT,
            &CreateWindowAux::new(),
        )
        .ok()?;
        conn.convert_selection(window, clipboard, targets, property, x11rb::CURRENT_TIME)
            .ok()?;
        conn.flush().ok()?;

        let deadline = Instant::now() + TIMEOUT;
        loop {
            match conn.poll_for_event().ok()? {
                Some(Event::SelectionNotify(event)) if event.requestor == window => {
                    // No property means nobody owns the clipboard, or the
                    // owner won't say what it offers.
                    if event.property == x11rb::NONE {
                        return Some(false);
                    }
                    break;
                }
                Some(_) => {}
                None if Instant::now() < deadline => thread::sleep(Duration::from_millis(5)),
                None => return None,
            }
        }
        let reply = conn
            .get_property(true, window, property, AtomEnum::ATOM, 0, u32::MAX)
            .ok()?
            .reply()
            .ok()?;
        let offered = reply.value32()?.any(|offered| offered == target);
        Some(offered)
    }
}

#[cfg(target_os = "macos")]
mod imp {
    use objc2_app_kit::NSPasteboard;

    /// The types from nspasteboard.org, and the marker 1Password has long
    /// used.
    const MARKERS: [&str; 4] = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ];

    pub fn change_count() -> Option<u64> {
        Some(NSPasteboard::generalPasteboard().changeCount() as u64)
    }

    pub fn is_concealed() -> bool {
        let Some(types) = NSPasteboard::generalPasteboard().types() else {
            return false;
        };
        types
            .to_vec()
            .iter()
            .any(|kind| MARKERS.contains(&kind.to_string().as_str()))
    }
}

#[cfg(windows)]
mod imp {
    use clipboard_win::raw::{is_format_avail, register_format, seq_num};

    /// Formats that password managers add to keep a copy out of clipboard
    /// history. Apps set `CanIncludeInClipboardHistory` to 0 to opt out, and
    /// hardly ever set it at all otherwise, so its presence is enough.
    const MARKERS: [&str; 3] = [
        "ExcludeClipboardContentFromMonitorProcessing",
        "CanIncludeInClipboardHistory",
        "Clipboard Viewer Ignore",
    ];

    pub fn change_count() -> Option<u64> {
        seq_num().map(|number| number.get().into())
    }

    pub fn is_concealed() -> bool {
        MARKERS
            .iter()
            .filter_map(|name| register_format(name))
            .any(|format| is_format_avail(format.get()))
    }
}

#[cfg(not(any(
    all(
        unix,
        not(any(target_os = "macos", target_os = "android", target_os = "emscripten"))
    ),
    target_os = "macos",
    windows
)))]
mod imp {
    pub fn change_count() -> Option<u64> {
        None
    }

    pub fn is_concealed() -> bool {
        false
    }
}
